name: Build

on:
  push:

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Clone web
        run: |
          git clone https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/${{ vars.GITLAB_GROUP }}/${{ vars.WEB_REPO }}.git

      - name: Change directory
        run: cd ${{ vars.WEB_REPO }}

      - name: Install dependencies
        run: npm ci

      - name: Create environment
        run: echo "VITE_API_URL=${{ vars.WEB_API_URL }}" > .env.local

      - name: Build web
        run: npm run build

  build-bin:
    runs-on: ubuntu-latest
    needs:
      - build-web
    steps:
      - name: Use golang 1.24.x
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: Clone openwrt
        run: |
          git clone https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/${{ vars.GITLAB_GROUP }}/${{ vars.BIN_REPO }}.git

      - name: Copy web
        run: cp ${{ vars.WEB_REPO }}/dist ${{ vars.BIN_REPO }}/internal/web

      - name: Change directory
        run: cd ${{ vars.BIN_REPO }}

      - name: Build arm64
        env:
          GOOS: "linux"
          GOARCH: "arm64"
        run: go build -v -trimpath -ldflags="-s -w" -o dist/zod-vpn-arm64

      - name: Build mips
        env:
          GOOS: "linux"
          GOARCH: "mipsle"
          GOMIPS: "softfloat"
        run: go build -v -trimpath -ldflags="-s -w" -o dist/zod-vpn-mips

